import { execFileSync } from "node:child_process";
import { readFileSync, writeFileSync } from "node:fs";
import { format, resolveConfig } from "prettier";

execFileSync("forge", ["build"], { stdio: "inherit" });
const artifact = JSON.parse(
  readFileSync(
    "contracts/out/PrivateTradeSettlement.sol/PrivateTradeSettlement.json",
    "utf8",
  ),
);
const target = "web/src/generated/private-trade-settlement.ts";
const output = await format(
  `// Generated by npm run abi:export. Do not edit.\nexport const settlementAbi = ${JSON.stringify(artifact.abi)} as const;\n`,
  { ...(await resolveConfig(target)), parser: "typescript" },
);
if (process.argv.includes("--check")) {
  if (readFileSync(target, "utf8") !== output)
    throw new Error("Settlement ABI is stale. Run npm run abi:export.");
  console.log("PASS: exported ABI matches compilation.");
} else writeFileSync(target, output);
